---
title: "REGENIE_output"
author: "zly"
date: "2023-02-08"
output: html_document
---

```{r}
library(qqman)
library(tidyverse)
library(tidyr)
```

```{r}
assoc_data <- read_table2(file = "data_regenie_out_firth_Phenotype.regenie", col_names = TRUE)

sum(-log10(assoc_data$LOG10P)>5)
assoc_data1 <- assoc_data[,c("CHROM","GENPOS","LOG10P")]
names(assoc_data1) <- c("CHR","BP","P")
# assoc_data2 <- assoc_data[,6]
# names(assoc_data2) <- c("P")
# assoc_data_sub <- cbine(assoc_data1,assoc_data2)
assoc_data_sub <- assoc_data1
assoc_data_sub <- tidyr::unite(assoc_data_sub,"SNP",CHR,BP,sep=":",remove=FALSE)
names(assoc_data_sub) <- c("SNP","CHR","BP","P")
assoc_data_sub$P <-as.numeric(assoc_data_sub$P)
manhattan(assoc_data_sub, logp=TRUE)
qq(assoc_data_sub$P, main = "Q-Q", xlim = c(0,22), ylim=c(0,7))
sum(-log10(assoc_data_sub$P)>5)
```

## Regenie for Binary traits(simulation)
```{r}

assoc_data <- read_table2(file = "data_regenie_out_binary_firth_Phenotype.regenie", col_names = TRUE)


assoc_data1 <- assoc_data[,c("CHROM","GENPOS","LOG10P")]
names(assoc_data1) <- c("CHR","BP","P")
# assoc_data2 <- assoc_data[,6]
# names(assoc_data2) <- c("P")
# assoc_data_sub <- cbine(assoc_data1,assoc_data2)
assoc_data_sub <- assoc_data1
assoc_data_sub <- tidyr::unite(assoc_data_sub,"SNP",CHR,BP,sep=":",remove=FALSE)
names(assoc_data_sub) <- c("SNP","CHR","BP","P")
assoc_data_sub$P <-as.numeric(assoc_data_sub$P)
# manhattan(assoc_data_sub, logp=TRUE)
qq(assoc_data_sub$P, main = "Q-Q", xlim = c(0,22), ylim=c(0,7))
sum(-log10(assoc_data_sub$P)>5)

```

